// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 1.0.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Confluent.Kafka.Examples.AvroSpecific
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    public partial class Player : ISpecificRecord
    {
        public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Player\",\"namespace\":\"Confluent.Kafka.Examples.AvroSpecific" +
                "\",\"fields\":[{\"name\":\"playername\",\"type\":\"string\"},{\"name\":\"playerid\",\"type\":[\"i" +
                "nt\",\"null\"]},{\"name\":\"city\",\"type\":[\"string\",\"null\"]}]}");
        private string _playername;
        private System.Nullable<int> _playerid;
        private string _city;
        public Schema Schema
        {
            get
            {
                return Player._SCHEMA;
            }
        }
        public string playername
        {
            get
            {
                return this._playername;
            }
            set
            {
                this._playername = value;
            }
        }
        public System.Nullable<int> playerid
        {
            get
            {
                return this._playerid;
            }
            set
            {
                this._playerid = value;
            }
        }
        public string city
        {
            get
            {
                return this._city;
            }
            set
            {
                this._city = value;
            }
        }
        public object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.playername;
                case 1: return this.playerid;
                case 2: return this.city;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.playername = (System.String)fieldValue; break;
                case 1: this.playerid = (System.Nullable<int>)fieldValue; break;
                case 2: this.city = (System.String)fieldValue; break;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
